### ISSUE TITLE
[Frontend] Focus-Pointing 좌표로 이미지 확대 

### ISSUE THREAD

**Issue by heehminh** [FLYAI4/ArtFront-ReactNative#10]
### 📌 Description
Focus Pointing 

<br>

### 🎈 Goal
<p>$\tiny{구체적인\ 산출물을\ 포함한\ 목표를\ 작성해주세요.}$</p>

- bounding box 클릭했을 때 확대되면서 설명띄우기

<br>

### ✏️ Todo
<p>$\tiny{목표\ 달성을\ 위해\ 해야할\ 일을\ 세부적으로\ 작성해주세요.}$</p>

- [x] json형태의 파일에서 keyword, 좌표, 설명뽑기 
- [x] 바운딩 박스 그리기
  - [x] 전체 이미지 크기와 현재 이미지 크기를 기준으로 비율 조정
  - [x] 새로운 좌표값 (new x1 = marginLeft + 비율*x1)
- [x] 클릭이벤트 (1) - keyword, 설명 텍스트 렌더링
- [x] 클릭이벤트 (2) - 바운딩 박스 확대 
  - [x] 좌표로 이미지 crop
  - [x] background-image opacity 수정
  - [ ] crop한 이미지, 해당 좌표에 배치하고 scale: 200%
