### ISSUE TITLE
[Frontend] camera image resize and crop 

### ISSUE THREAD

**Issue by heehminh** [FLYAI4/ArtFront-ReactNative#15]
### 📌 Description
image crop and resize 

<br>

### 🎈 Goal
<p>$\tiny{구체적인\ 산출물을\ 포함한\ 목표를\ 작성해주세요.}$</p>

- document-scnner-plugin 을 이용하여 image resize and crop 
<br>

### ✏️ Todo
<p>$\tiny{목표\ 달성을\ 위해\ 해야할\ 일을\ 세부적으로\ 작성해주세요.}$</p>

- [x] 카메라로 찍기
  - [x] 카메라 버튼 클릭 -> 사진으로 찍기 연결
  - [x] 찍은 이미지 받아오기 
  - [x] 사진찍으면 전체 설명 나레이션으로 이동
