### ISSUE TITLE
[Frontend] 메인콘텐츠 나레이션 TTS  

### ISSUE THREAD

**Issue by heehminh** [FLYAI4/ArtFront-ReactNative#25]
### 📌 Description
메인콘텐츠 나레이션 TTS 

<br>

### 🎈 Goal
<p>$\tiny{구체적인\ 산출물을\ 포함한\ 목표를\ 작성해주세요.}$</p>

- 메인콘텐츠 TTS 기능 
- 재생, 일시중지 버튼 

<br>

### ✏️ Todo
<p>$\tiny{목표\ 달성을\ 위해\ 해야할\ 일을\ 세부적으로\ 작성해주세요.}$</p>

- [x] TTS 라이브러리 리서치 (`react-native-sound`, `react-native-sound-player`)
- [x] mp3 내부파일시스템에 저장 
- [x] 재생, 일시중지 버튼 구현
- [ ] 오디오에 맞춰서 스크롤 구현

**Comment by heehminh** [comment]
# 1. react-native-sound-player
[react-native-sound-player github](https://github.com/johnsonsu/react-native-sound-player)

# 2. mp3 파일 저장 경로
`ios/art/`

# 3. 일시중지 
- 재생 버튼 눌렀을 때: 오디오 재생 + 재생 버튼 일시중지로 변경 
- 일시중지 버튼 눌렀을 때: 중지된 지점부터 다시 오디오 재생 + 버튼 재생으로 변경
- 해당 페이지를 벗어났을 때: 오디오 중지 
  - 이렇게 오디오를 중지했을 경우 버튼 텍스트를 일시중지 -> 재생으로 바꿔놔야함 (이전페이지로 돌아갔을 때를 고려하여)
