### ISSUE TITLE
[Frontend] 메인콘텐츠 나레이션에 맞춘 스크롤 

### ISSUE THREAD

**Issue by heehminh** [FLYAI4/ArtFront-ReactNative#28]
### 📌 Description
메인콘텐츠 나레이션 

<br>

### 🎈 Goal
<p>$\tiny{구체적인\ 산출물을\ 포함한\ 목표를\ 작성해주세요.}$</p>

- 메인콘텐츠가 나레이션되고 있을 때 나레이션에 맞춰서 스크롤되게 (내용이 안잘리게)

<br>

### ✏️ Todo
<p>$\tiny{목표\ 달성을\ 위해\ 해야할\ 일을\ 세부적으로\ 작성해주세요.}$</p>

- [x] design: 스크롤뷰 높이 고정 
- [x] 메인콘텐츠 나레이션에 맞춘 텍스트 스크롤 (현재 재생되고 있는 초 / 총 길이 * 높이 형식으로 scrollTo y를 설정하면 될 것 같음)
- [x] 끝까지 재생했을 때 이벤트
   - [x] 일시중지 -> 재생으로 버튼 텍스트 변경
   - [x] 스크롤 끝에 도달하면 멈춤 (현재는 처음으로 돌아감)
- [x] 중간에 다른 페이지로 이동했을 때 이벤트
   - [x] 일시중지 -> 재생으로 버튼 텍스트 변경
