### ISSUE TITLE
[Frontend] 멀티미디어 이진 데이터 처리 학습 

### ISSUE THREAD

**Issue by heehminh** [FLYAI4/ArtFront-ReactNative#6]
### 📌 Description
이미지, 비디오 같은 멀티미디어 데이터를 이진 데이터로 처리하는 방법을 학습합니다. 

<br>

### 🎈 Goal
<p>$\tiny{구체적인\ 산출물을\ 포함한\ 목표를\ 작성해주세요.}$</p>

- Base64
- Blob (Binary Large Object)
- ArrayBuffer

<br>

### ✏️ Todo
<p>$\tiny{목표\ 달성을\ 위해\ 해야할\ 일을\ 세부적으로\ 작성해주세요.}$</p>

- [x] Base64
  - [x] 이미지 URL을 base64로 변환하기 
- [x] Blob
  - [x] Blob -> ObjectURL 변환하기 
  - [x] Blob -> Base64 변환하기
- [x] ArrayBuffer 
- [x] File & FileReader

**Comment by heehminh** [comment]
# Base64
- 별도 이미지 파일이 필요없다. 변수에 저장한 base64 데이터 자체가 이미지이기 때문이다.
- 브라우저 렌더링시, 문서로딩과 같이 로딩 되기에 끊기지 않고 불러온다. 또한 네트워크가 좋지않아도 위와 같은 특징으로 이미지를 로딩할 수 있다.
- 원본보다 33%의 용량이 커져서, 남용할 경우 오히리 로딩 속도가 저하될 수 있다. 

자바스크립트 코드를 이용해 이미지를 변환하는 방법
```js
(async () => {
    const data = await fetch('https://play-lh.googleusercontent.com/hYdIazwJBlPhmN74Yz3m_jU9nA6t02U7ZARfKunt6dauUAB6O3nLHp0v5ypisNt9OJk');
    const blob = await data.blob();
    const reader = new FileReader();
    reader.onload = () => {
        const base64data = reader.result;
        console.log(base64data)
    }
    reader.readAsDataURL(blob);
})()
```
먼저 fetch api 로 이미지를 읽어들이고, 이미지를 blob 형식으로 변환한다. 그리고 FileReader 객체를 통해 blob 데이터를 base64 형식으로 읽어들여 변환시킨다. 



# Blob (Binary Large Object)
blob은 주로 이미지, 오디오, 비디오와 같은 멀티미디어 파일 바이너리를 객체 형태로 저장한 것이다. 멀티미디어 파일들은 대다수 용량이 큰 경우가 많기 때문에, 이를 데이터베이스에 효과적으로 저장하기 위해 고안된 자료형이다.  
<img width="553" alt="image" src="https://github.com/FLYAI4/ArtFront-ReactNative/assets/76530562/1c82d66d-aa78-4d22-bdef-0d674f889063">

- base64는 바이너리 데이터를 다루기 위해 **텍스트** 형태로 저장한 포맷이다.
- blob은 바이너리 데이터를 다루기 위해 **객체**를 저장하는 것이다. 

또한 blob은 객체이기 때문에 base64로 변환할 수도 있고 buffer로도 변환할 수 있다. 

## Blob -> ObjectURL 변환 
blob 객체는 <a>, <img> 태그의 src 에 사용할 수 있는 url 타입으로 따로 변환을 해야한다. 
```html
<img src="" alt="" style="width:150px; display: block;"> 
<a download="img.jpg" href="#">이미지 다운로드</a>

<script>
    fetch('https://www.business2community.com/wp-content/uploads/2014/04/Free.jpg')
      .then((response) => response.blob())
      .then((blob) => {
        const url = URL.createObjectURL(blob);
        document.querySelector('img').src = url;
        document.querySelector('a').href = url;
      });
</script>
```

변환된 URL은 현재 탭의 브라우저 메모리에 저장되고, 저장된 URL은 매핑된 Blob 객체를 참고하고 있는 형태이다. 
Blob 객체가 URL로 변환되어 매핑이 이루어진 채 메모리에 저장되게 되면, 명시적으로 해당 URL이 해제되기 전까지 브라우저는 해당 URL이 유효하다고 판단하기 때문에 자바스크립트 엔진에서 가비지 컬렉션이 이루어지지 않는다. 따라서 blob URL을 사용한 이후, 더 이상 사용하지 않을 시점이라고 판단되면 명시적으로 해제해주는 것이 좋다.
```jsx
// Create Blob URL
const objectURL = window.URL.createObjectURL(blob);

// Revoke Blob URL after DOM updates..
window.URL.revokeObjectURL(objectURL);
```
변환은 `URL.createObjectURL` 메서드를 통해 진행했고, 해제의 경우에는 `URL.revokeObjectURL` 메서드를 사용한다.

**Comment by heehminh** [comment]
# ArrayBuffer 
ArrayBuffer 객체는 이미지, 동영상과 같은 멀티미디어 데이터 덩어리를 표준 자바스크립트에서 다루기 위해 도입됐다. 일반적으로 실시간 방송과 같이 영상내용을 송출할 때에는, 영상이라고 하는 실시간 데이터를 계속해서 전달해줘야 유저들이 볼 수 있다. -> 어떤 식으로든 커다란 데이터를 잘개 쪼개서 전송해야 하는 상황 발생 

`buffer`: 일성 구획만큼의 데이터를 쪼개서 전달되는 stream을 저장한 후 일정 크기가 도달하면 출력장치나 동영상 플레이어로 저달해주는 중개자 역할을 하는 객체 
`ArrayBuffer`: **바이너리 데이터**를 직접 다루는 수단, 메모리를 개발자가 수동으로 관리할 수 있게 해준다.
base64, blob은 사람이 읽고 다루기 편하게 가공된 데이터 타입이라면, ArrayBuffer는 보다 오리지널에 가깝다. 레퍼런스 타입으로 되어있고, 고정된 길이의 연속된 메모리 공간을 할당해 사용하겠다고 알려주는 역할을 한다. (AudioBuffer, SourceBuffer)
```js
let buffer = new ArrayBuffer(16); // 16 바이트 크기의 buffer를 생성
buffer.byteLength; // 16
```
ArrayBuffer와 자바스크립트의 배열 차이점
- 고정길이를 가지고 있고, 이를 늘이거나 줄일 수 없다.
- 정확히 명시된 크기만큼의 공간을 메모리에서 차지한다.
- 각각의 바이트에 접근하기 위해서는, 일반 배열처럼 buffer[index]와 같이 인덱스를 통해 접근할 수 없다. 대신에 view라고 불리는 별도의 객체를 생성해서 접근해야 한다.
```js
// view를 통해 값을 입력
view[0] = 123456; // 분할공간 중 첫번째에 123456이라는 숫자데이터를 넣는다

for (let num of view) {
  console.log(num);	// 123456, 0, 0, 0
}
```

## Base64 -> ArrayBuffer -> Blob 
base64 데이터를 blob으로 바꾸기 위해 중간 과정으로 arrayBuffer가 쓰인다. 
```js
const b64toBlob = (b64Data, contentType='', sliceSize=5121) => {
   const image_data = atob(b64Data.split(',')[1]); // data:image/gif;base64 필요없으니 떼주고, base64 인코딩을 풀어준다

   const arraybuffer = new ArrayBuffer(image_data.length);
   const view = new Uint8Array(arraybuffer);

   for (let i = 0; i < image_data.length; i++) {
      view[i] = image_data.charCodeAt(i) & 0xff;
      // charCodeAt() 메서드는 주어진 인덱스에 대한 UTF-16 코드를 나타내는 0부터 65535 사이의 정수를 반환
      // 비트연산자 & 와 0xff(255) 값은 숫자를 양수로 표현하기 위한 설정
   }

   return new Blob([arraybuffer], { type: contentType });

const contentType = 'image/png';
const b64Data = 'data:image/gif;base64,R0....'

const blob = b64toBlob(b64Data, contentType); // base64 -> blob
const blobUrl = URL.createObjectURL(blob); // object URL 생성 

const img = document.createElement('img');
img.src = blobUrl;
document.body.appendChild(img);
} 
```

## Blob -> ArrayBuffer 
1. 정통적인 FileReader 객체로 변환 
    ```js
    let fileReader = new FileReader();
    
    fileReader.readAsArrayBuffer(blob); // ArrauBuffer 형태로 데이터를 읽어 변환
    
    fileReader.onload = function(event) {
      let arrayBuffer = fileReader.result;
    };
    ```

2. 대용량 blob일 경우 프로미스를 이용해 비동기 처리 
    ```js
    const blob = new Blob(...);
    const buf = await blob.arrayBuffer(); // 비동기로 arrayBuffer로 변환 (대용량 일경우)
    ```

3. (편법) blob을 ObjectURL로 바꾸고 fetch로 요청해 한방에 arrayBuffer로 변환 
    ```js
    fetch(URL.createObjectURL(myBlob))
	    .then(res => res.arrayBuffer())
    ```

# 서버단에서 이미지 가져와 다루기 
```js
const fetch = require('node-fetch');

//* 이미지 가져오기
const img = await fetch('이미지URL 혹은 base64이미지') // 이미지 url을 fetch
  .then((res) => res.blob()) // 반환 이미지를 blob으로 변환
  .then(async (blob) => {
     const arrayBuffer = await blob.arrayBuffer(); // blob을 arrayBuffer로 변환
     return Buffer.from(arrayBuffer); // 클라이언트용 버퍼인 arrayBuffer룰 다시 서버용 buffer로 변환
  });
```
1. 이미지를 `fetch` 한다. 
2. 결과값을 blob으로 변환한다.
3. blob을 비동기를 통해 arraybuffer로 변환한다.
4. arraybuffer을 buffer로 변환해준다 (blob을 buffer로 바로 변환할 수 없기 때문에)

fetch 모듈에서 바로 버퍼로 변환할 수 있는 헬퍼 메서드 
```js
const fetch = require('node-fetch');

const img = await fetch(이미지URL 혹은 base64이미지) // 이미지 url을 fetch
      .then((res) => res.buffer()) // 반환 이미지를 blob으로 변환
```

**Comment by heehminh** [comment]
# File & FileReader 
자바스크립트에서의 File 객체는 Blob 객체를 확장한 객체로 주로 파일시스템과 관련된 기능을 담당한다.
1. File 객체 이용 
    ```js
    new File(fileParts, fileName, [options]);
    ```
    - fileParts: Blob / BufferSource / String과 같은 배열 
    - fileName: 파일 이름 (문자열)
    - options - lastModified: 마지막 수정이 일어난 때의 timestamp 

3. html의 input태그 이용 
      ```html
      <input type="file" onchange="showFile(this)"/>
      
      <script>
        function showFile(input) {
          let file = input.files[0];
          
          console.log(`File name: ${file.name}`);  // 파일 이름
          console.log(`Last modified: ${file.lastModified}`);  // 수정이 일어난 때의 timeStamp
        }
      </script>
      ```
      `input type='file'` 의 경우 추가적으로 multiple 옵션을 지정할 수 있는데 이 경우에는 다량의 File이 배열 형태로 전달되게 된다.
      이때를 고려하여 단일 파일만 전달되는 경우에도 File은 항상 유사 배열로 전달되기 때문에 하나의 파일만 다루는 경우에도 인덱스로 접근하는 것에 주의하자 

## FileReader 객체 
Blod 또는 File과 같은 객체로부터 데이터를 읽어들이기위한 목적으로 사용되는 객체이다.
주요 메서드
```js
const reader = new FileReader();

reader.readAsArrayBuffer(blob); // --- (1) 
reader.readAsText(blob, [encoding]) // --- (2)
reader.readAsDataURL(blob); // --- (3)
```
1. `readAsArrayBuffer(blob)`: ArrayBuffer 형태로 데이터를 읽음 
   - readAsArrayBuffer의 경우 바이너리 파일 대상으로 로우 레벨의 바이너리 작업이 필요한 경우에 유용하다. 대부분 하이레벨에서 하는 작업의 경우엔 File 객체가 Blob을 상속받고 있기 때문에 별도의 읽기 과정없이 즉각적으로 slice 등의 메서드 호출이 가능하다. 

2. `readAsText(blob, [encoding])`: encoding 방식에 맞게 텍스트 형태로 데이터를 읽음 (default: utf-8)
   - readAsText의 경우 텍스트 형태의 문자열이 필요한 경우 유용하다. 

3. `readAsDataURL(blob)`: base64 형태의 data url로 데이터를 읽음
   - readAsDataURL의 경우 img 태그와 같이 src 속성에 리소스를 다루어야 하는 경우 유용하다. 또는 `URL.createObjectURL`을 이용하는 방법도 있다. 

4. `abort()`: 작업을 즉시 중단
