### ISSUE TITLE
[Frontend] 로그인, 회원가입 UI 

### ISSUE THREAD

**Issue by heehminh** [FLYAI4/ArtFront-ReactNative#8]
### 📌 Description

<img width="452" alt="image" src="https://github.com/FLYAI4/ArtFront-ReactNative/assets/76530562/4f75593f-447b-4946-a3b8-8647eeb833a7">

<br>

### 🎈 Goal
<p>$\tiny{구체적인\ 산출물을\ 포함한\ 목표를\ 작성해주세요.}$</p>

- 로그인, 회원가입 UI
- 회원가입 정규식 

<br>

### ✏️ Todo
<p>$\tiny{목표\ 달성을\ 위해\ 해야할\ 일을\ 세부적으로\ 작성해주세요.}$</p>

- [x] ~~react hook form native 사용법 리서치~~ -> 직접 구현하기로 결정
- [x] UI
  - [x] 로그인 UI
  - [x] 회원가입 UI
  - [x] 헤더 
- [x] 회원가입 정규식 처리 
  - [x] 이메일 (id): @가 있는지, 이메일 필드에는 숫자, 영어, 일부 특수문자(@와 .)만 허용 
  - [x] 비밀번호: 숫자+문자, 6-12글자, 비밀번호와 비밀번호확인이 동일한지
  - [x] 동의: 전체 동의와 선택 동의
